# Generated by Django 4.0.6 on 2022-07-16 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_image_admin_image_student_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='last_update',
            new_name='last_updated',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='last_update',
            new_name='last_updated',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='last_update',
            new_name='last_updated',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='last_update',
            new_name='last_updated',
        ),
    ]
