# Generated by Django 4.0.6 on 2022-07-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_last_update_admin_last_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
