# Generated by Django 4.0.6 on 2022-07-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_student_grade_student_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
    ]
