# Generated by Django 4.0.6 on 2022-07-17 22:12

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_student_city_alter_student_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
