# Generated by Django 4.0.6 on 2022-07-20 06:39

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_student_image_alter_teacher_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, upload_to=accounts.models.location),
        ),
    ]
