# Generated by Django 4.0.6 on 2022-07-20 07:13

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, default='profile_pics/default.jpg', upload_to=accounts.models.location),
        ),
    ]
