# Generated by Django 4.0.6 on 2022-07-20 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_student_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
    ]
