# Generated by Django 4.0.6 on 2022-07-20 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_teacher_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='area',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='city',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='country',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='flat',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='house',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='road',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='state',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='zip',
        ),
    ]
