# Generated by Django 4.0.6 on 2022-07-21 16:28

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_student_user_alter_teacher_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='image',
            field=models.ImageField(blank=True, default='profile_pics/default.jpg', upload_to=accounts.models.location),
        ),
        migrations.AlterField(
            model_name='admin',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='admin', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
