# Generated by Django 4.0.6 on 2022-07-21 16:28

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('production_house', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('batch', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='session', chained_model_field='session', on_delete=django.db.models.deletion.PROTECT, related_name='resources', to='production_house.batch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resources', to='production_house.course')),
                ('session', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='course', chained_model_field='course', on_delete=django.db.models.deletion.PROTECT, related_name='resources', to='production_house.session')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='production_house.resource')),
            ],
        ),
    ]
