# Generated by Django 4.0.6 on 2022-07-21 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_house', '0002_resource_resourcefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcefile',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
