# Generated by Django 4.0.6 on 2022-07-21 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_house', '0003_resourcefile_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcefile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
    ]
