# Generated by Django 4.0.6 on 2022-07-22 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_house', '0004_alter_resourcefile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
        migrations.DeleteModel(
            name='ResourceFile',
        ),
    ]
