# Generated by Django 4.0.6 on 2022-07-22 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production_house', '0005_resource_files_delete_resourcefile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='files',
        ),
        migrations.CreateModel(
            name='ResourceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='files')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='production_house.resource')),
            ],
        ),
    ]
