# Generated by Django 4.0.6 on 2022-07-22 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production_house', '0006_remove_resource_files_resourcefile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResourceFile',
            new_name='File',
        ),
    ]
