# Generated by Django 4.0.6 on 2022-07-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_house', '0008_rename_description_resource_content_resource_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='type',
            field=models.CharField(choices=[('I', 'Image'), ('V', 'Video'), ('A', 'Audio'), ('D', 'Document')], default='I', max_length=1),
            preserve_default=False,
        ),
    ]
