# Generated by Django 4.0.6 on 2022-07-26 04:07

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('production_house', '0009_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
