# Generated by Django 4.0.6 on 2022-07-26 15:56

from django.db import migrations
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('production_house', '0010_alter_resource_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='batch',
        ),
        migrations.AddField(
            model_name='resource',
            name='batch',
            field=smart_selects.db_fields.ChainedManyToManyField(auto_choose=True, chained_field='session', chained_model_field='session', related_name='resources', to='production_house.batch'),
        ),
    ]
