# Generated by Django 4.0.6 on 2022-07-26 16:40

from django.db import migrations
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('production_house', '0011_remove_resource_batch_resource_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='batch',
        ),
        migrations.AddField(
            model_name='resource',
            name='batches',
            field=smart_selects.db_fields.ChainedManyToManyField(auto_choose=True, chained_field='session', chained_model_field='session', horizontal=True, related_name='resources', to='production_house.batch'),
        ),
    ]
