# Generated by Django 4.1.5 on 2023-02-07 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_house', '0012_remove_resource_batch_resource_batches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='title',
            field=models.CharField(blank=True, default='Untitled', max_length=255, null=True),
        ),
    ]
