# Generated by Django 4.1.5 on 2023-02-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_house', '0013_alter_resource_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='title',
            field=models.CharField(blank=True, default='Untitled', max_length=255, null=True),
        ),
    ]
